name: Cleanup Stale Deployments

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to clean up (optional)'
        required: false
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get branch name
        id: branch-name
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          elif [[ -n "${{ github.event.inputs.branch }}" ]]; then
            BRANCH_NAME="${{ github.event.inputs.branch }}"
          else
            echo "No branch specified for cleanup"
            exit 1
          fi
          
          # Convert branch name to URL-friendly format
          SAFE_BRANCH=$(echo "$BRANCH_NAME" | sed 's/\//-/g')
          echo "DEPLOY_PATH=$SAFE_BRANCH" >> $GITHUB_ENV
          echo "Branch to clean up: $SAFE_BRANCH"

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Delete deployment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const deployPath = process.env.DEPLOY_PATH;
            if (!deployPath) {
              console.log('No deployment path specified');
              return;
            }
            
            console.log(`Attempting to delete deployment for: ${deployPath}`);
            
            try {
              // This is a simplified approach - GitHub Pages doesn't have a direct API
              // for deleting specific paths. In a real implementation, you might need
              // to use a more sophisticated approach or custom deployment solution.
              
              // For now, we'll just log the intent
              console.log(`Would delete deployment at path: ${deployPath}`);
              console.log('Note: GitHub Pages doesn\'t support selective path deletion natively.');
              console.log('To fully implement this, consider using a custom deployment solution.');
            } catch (error) {
              console.error('Error during cleanup:', error);
            }