name: Deploy to GitHub Pages

on:
  push:
    branches: [main, dev, test]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment per branch
concurrency:
  group: "pages-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set branch-specific environment variables
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          
          if [ "$BRANCH_NAME" = "main" ]; then
            echo "NEXT_PUBLIC_BASE_PATH=/mita-state-self-assessment-tool" >> $GITHUB_ENV
          elif [ "$BRANCH_NAME" = "dev" ]; then
            echo "NEXT_PUBLIC_BASE_PATH=/mita-state-self-assessment-tool/dev" >> $GITHUB_ENV
          elif [ "$BRANCH_NAME" = "test" ]; then
            echo "NEXT_PUBLIC_BASE_PATH=/mita-state-self-assessment-tool/test" >> $GITHUB_ENV
          fi

      - name: Build and Export
        run: |
          npm run build
          touch out/.nojekyll

      - name: Organize branch-specific output
        run: |
          if [ "$BRANCH_NAME" = "dev" ]; then
            # Create dev directory and move files
            mkdir -p out/dev
            cp -r out/*.* out/dev/ || true
            cp -r out/_next out/dev/ || true
            # Keep only necessary files in root
            find out -maxdepth 1 -not -name dev -not -name test -not -name "." -not -name ".." -not -name ".nojekyll" -not -name "_next" | xargs rm -rf || true
          elif [ "$BRANCH_NAME" = "test" ]; then
            # Create test directory and move files
            mkdir -p out/test
            cp -r out/*.* out/test/ || true
            cp -r out/_next out/test/ || true
            # Keep only necessary files in root
            find out -maxdepth 1 -not -name dev -not -name test -not -name "." -not -name ".." -not -name ".nojekyll" -not -name "_next" | xargs rm -rf || true
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages