name: Deploy to GitHub Pages

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build && npm run export
        
      - name: Configure base path
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            # Main branch - deploy to root
            echo "No base path adjustment needed for main branch"
          else
            # For other branches, create a subfolder with branch name
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            echo "Configuring for branch: $BRANCH_NAME"
            # For Next.js, we need to adjust the basePath in next.config.js
            # This is a simple sed replacement - you might need to adjust based on your config
            sed -i "s|basePath: '',|basePath: '/$BRANCH_NAME',|g" next.config.js
            npm run build && npm run export
            mkdir -p out/$BRANCH_NAME
            find out -maxdepth 1 -not -path "out/$BRANCH_NAME" -not -path "out" -exec cp -r {} out/$BRANCH_NAME/ \;
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
          clean: true
          clean-exclude: |
            staging/**
            preview/**
            
      - name: Output Deployment URL
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "::notice::🚀 Deployed to: https://$(echo ${{ github.repository_owner }}).github.io/$(echo ${{ github.event.repository.name }})"
          else
            echo "::notice::🚀 Deployed to: https://$(echo ${{ github.repository_owner }}).github.io/$(echo ${{ github.event.repository.name }})/$BRANCH_NAME"
          fi